// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RecoveryApp.Infrastructure.Persistence;

#nullable disable

namespace RecoveryApp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260907203943_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RecoveryApp.Domain.Entities.AudioTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("audio_url");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("boolean")
                        .HasColumnName("is_premium");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_audio_tracks");

                    b.HasIndex("Category", "IsPremium")
                        .HasDatabaseName("ix_audio_tracks_category_is_premium");

                    b.ToTable("audio_tracks", (string)null);
                });

            modelBuilder.Entity("RecoveryApp.Domain.Entities.EnergyCheckin", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Context")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("context");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_at");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_energy_checkins");

                    b.HasIndex("UserId", "RecordedAt")
                        .HasDatabaseName("ix_energy_checkins_user_id_recorded_at");

                    b.HasIndex("UserId", "UpdatedAt")
                        .HasDatabaseName("ix_energy_checkins_user_id_updated_at");

                    b.ToTable("energy_checkins", null, t =>
                        {
                            t.HasCheckConstraint("ck_energy_checkins_score", "score BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("RecoveryApp.Domain.Entities.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("endpoint");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("response_body");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.HasKey("UserId", "Key")
                        .HasName("pk_idempotency_records");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_idempotency_records_created_at");

                    b.ToTable("idempotency_records", (string)null);
                });

            modelBuilder.Entity("RecoveryApp.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId", "ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_user_id_expires_at");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("RecoveryApp.Domain.Entities.SyncChangelog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("changed_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entity_name");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("operation");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sync_changelog");

                    b.HasIndex("UserId", "ChangedAt")
                        .HasDatabaseName("ix_sync_changelog_user_id_changed_at");

                    b.ToTable("sync_changelog", (string)null);
                });

            modelBuilder.Entity("RecoveryApp.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppleUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("apple_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("AppleUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_apple_user_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email")
                        .HasFilter("email IS NOT NULL AND deleted_at IS NULL");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("RecoveryApp.Domain.Entities.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActualDurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("actual_duration_seconds");

                    b.Property<DateTimeOffset>("ClientCreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("client_created_at");

                    b.Property<bool>("CompletedSuccessfully")
                        .HasColumnType("boolean")
                        .HasColumnName("completed_successfully");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ended_at");

                    b.Property<int>("InterruptionsCount")
                        .HasColumnType("integer")
                        .HasColumnName("interruptions_count");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("session_type");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<int>("TargetDurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("target_duration_seconds");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_sessions");

                    b.HasIndex("UserId", "StartedAt")
                        .HasDatabaseName("ix_user_sessions_user_id_started_at");

                    b.HasIndex("UserId", "UpdatedAt")
                        .HasDatabaseName("ix_user_sessions_user_id_updated_at");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("RecoveryApp.Domain.Entities.UserSettings", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("CaffeineCutoffHours")
                        .HasColumnType("integer")
                        .HasColumnName("caffeine_cutoff_hours");

                    b.Property<int>("DigitalSunsetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("digital_sunset_minutes");

                    b.Property<bool>("HapticEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("haptic_enabled");

                    b.Property<string>("SoundMixConfig")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("sound_mix_config");

                    b.Property<TimeOnly>("TargetSleepTime")
                        .HasColumnType("time")
                        .HasColumnName("target_sleep_time");

                    b.Property<TimeOnly>("TargetWakeTime")
                        .HasColumnType("time")
                        .HasColumnName("target_wake_time");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("pk_user_settings");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_user_settings_updated_at");

                    b.ToTable("user_settings", (string)null);
                });

            modelBuilder.Entity("RecoveryApp.Domain.Entities.EnergyCheckin", b =>
                {
                    b.HasOne("RecoveryApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_energy_checkins_users_user_id");
                });

            modelBuilder.Entity("RecoveryApp.Domain.Entities.IdempotencyRecord", b =>
                {
                    b.HasOne("RecoveryApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_idempotency_records_users_user_id");
                });

            modelBuilder.Entity("RecoveryApp.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("RecoveryApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");
                });

            modelBuilder.Entity("RecoveryApp.Domain.Entities.SyncChangelog", b =>
                {
                    b.HasOne("RecoveryApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sync_changelog_users_user_id");
                });

            modelBuilder.Entity("RecoveryApp.Domain.Entities.UserSession", b =>
                {
                    b.HasOne("RecoveryApp.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_sessions_users_user_id");
                });

            modelBuilder.Entity("RecoveryApp.Domain.Entities.UserSettings", b =>
                {
                    b.HasOne("RecoveryApp.Domain.Entities.User", "User")
                        .WithOne("Settings")
                        .HasForeignKey("RecoveryApp.Domain.Entities.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_settings_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecoveryApp.Domain.Entities.User", b =>
                {
                    b.Navigation("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
